// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file user.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from '@bufbuild/protobuf/codegenv1'
import { fileDesc, messageDesc, serviceDesc } from '@bufbuild/protobuf/codegenv1'
import type { Message } from '@bufbuild/protobuf'

/**
 * Describes the file user.proto.
 */
export const file_user: GenFile =
  /*@__PURE__*/
  fileDesc(
    'Cgp1c2VyLnByb3RvEgR1c2VyIh4KC1VzZXJSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAkiPQoRQ3JlYXRlVXNlclJlcXVlc3QSDAoEbmFtZRgBIAEoCRINCgVlbWFpbBgCIAEoCRILCgNhZ2UYAyABKAUiSQoMVXNlclJlc3BvbnNlEg8KB3VzZXJfaWQYASABKAkSDAoEbmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRILCgNhZ2UYBCABKAUyggEKC1VzZXJTZXJ2aWNlEjYKC0dldFVzZXJJbmZvEhEudXNlci5Vc2VyUmVxdWVzdBoSLnVzZXIuVXNlclJlc3BvbnNlIgASOwoKQ3JlYXRlVXNlchIXLnVzZXIuQ3JlYXRlVXNlclJlcXVlc3QaEi51c2VyLlVzZXJSZXNwb25zZSIAQglaBy4vO3VzZXJiBnByb3RvMw'
  )

/**
 * 请求参数
 *
 * @generated from message user.UserRequest
 */
export type UserRequest = Message<'user.UserRequest'> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string
}

/**
 * Describes the message user.UserRequest.
 * Use `create(UserRequestSchema)` to create a new message.
 */
export const UserRequestSchema: GenMessage<UserRequest> = /*@__PURE__*/ messageDesc(file_user, 0)

/**
 * @generated from message user.CreateUserRequest
 */
export type CreateUserRequest = Message<'user.CreateUserRequest'> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string

  /**
   * @generated from field: string email = 2;
   */
  email: string

  /**
   * @generated from field: int32 age = 3;
   */
  age: number
}

/**
 * Describes the message user.CreateUserRequest.
 * Use `create(CreateUserRequestSchema)` to create a new message.
 */
export const CreateUserRequestSchema: GenMessage<CreateUserRequest> =
  /*@__PURE__*/
  messageDesc(file_user, 1)

/**
 * 响应结构
 *
 * @generated from message user.UserResponse
 */
export type UserResponse = Message<'user.UserResponse'> & {
  /**
   * @generated from field: string user_id = 1;
   */
  userId: string

  /**
   * @generated from field: string name = 2;
   */
  name: string

  /**
   * @generated from field: string email = 3;
   */
  email: string

  /**
   * @generated from field: int32 age = 4;
   */
  age: number
}

/**
 * Describes the message user.UserResponse.
 * Use `create(UserResponseSchema)` to create a new message.
 */
export const UserResponseSchema: GenMessage<UserResponse> = /*@__PURE__*/ messageDesc(file_user, 2)

/**
 * 用户服务定义
 *
 * @generated from service user.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.UserService.GetUserInfo
   */
  getUserInfo: {
    methodKind: 'unary'
    input: typeof UserRequestSchema
    output: typeof UserResponseSchema
  }
  /**
   * @generated from rpc user.UserService.CreateUser
   */
  createUser: {
    methodKind: 'unary'
    input: typeof CreateUserRequestSchema
    output: typeof UserResponseSchema
  }
}> = /*@__PURE__*/ serviceDesc(file_user, 0)
